version: '3.7'

services:
  node:
    image: node:10.13-alpine
    container_name: node
    tty: true
    init: true
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    working_dir: /app

  postgres:
    image: postgres:10.5
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_DB: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

  pgweb:
    image: donnex/pgweb
    restart: always
    ports:
      - 8081:8080
    command: -s --bind=0.0.0.0 --listen=8080 --url postgresql://docker:docker@postgres/docker?sslmode=disable
    depends_on:
      - postgres

  redis:
    image: redis:5.0
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  redisCommander:
    image: tenstartups/redis-commander
    command: --redis-host redis
    ports:
      - 8082:8081

volumes:
  postgres_data:
  redis_data:
